version: 2
sources:
  - name: "src"
    database: "database"
    schema: "schema"
    tables:
      - name: "tab"
        identifier: "table"
        columns:
          - name: "cents"
            type: "INT64"
          - name: "id"
            type: "STRING"
          - name: "first_name"
            type: "STRING"
          - name: "last_name"
            type: "STRING"